#!/usr/bin/env bash
# Terminate script if there is an error

set -ev

sleep 1
sleep 1
sleep 1
ruby tests.rb http://localhost:4000/index.html
ruby tests.rb http://localhost:4000/PokemonGo/index.html
ruby tests.rb http://localhost:4000/PokemonGo/PokemonGoStrings.html
ruby tests.rb http://localhost:4000/PokemonGo/old/PokemonGoStrings.html	
ruby tests.rb http://localhost:4000/PokemonGo/old/PokemonGoStringsFull.html
ruby tests.rb http://localhost:4000/PyHDDKeepAlive/index.html
ruby tests.rb http://localhost:4000/amp/index.html