#!/usr/bin/env bash
# Terminate script if there is an error

set -e

# Node Project Manager

echo -e "Installing AMP Validator"
npm install -g amphtml-validator

# Jekyll compile and start server

echo -e "Building Jekyll and setting up server"
bundle exec jekyll serve &

sleep 6
# HTML Proofer

echo -e "Testing HTML and links of the frontpage"
bundle exec htmlproofer http://localhost:4000/index.html --as-links

echo -e "Testing HTML and links of the Pokemon Go resource disambiguation page"
bundle exec htmlproofer http://localhost:4000/PokemonGo/index.html --as-links

echo -e "Testing HTML and links of the current Pokemon Go strings page"
bundle exec htmlproofer http://localhost:4000/PokemonGo/PokemonGoStrings.html --as-links

echo -e "Testing HTML and links of the Pokemon Go strings at launch"
bundle exec htmlproofer http://localhost:4000/PokemonGo/old/PokemonGoStrings.html --as-links

echo -e "Testing HTML and links of the expanded Pokemon Go strings at launch"
bundle exec htmlproofer http://localhost:4000/PokemonGo/old/PokemonGoStringsFull.html --as-links

echo -e "Testing HTML and links of the PyHDDKeepAlive homepage"
bundle exec htmlproofer http://localhost:4000/PyHDDKeepAlive/index.html --as-links

echo -e "Testing HTML and links of the AMP frontpage"
bundle exec htmlproofer http://localhost:4000/amp/index.html --as-links

# AMP Validator

echo -e "Verifying AMP formatting of AMP frontpage"
amphtml-validator http://localhost:4000/amp/index.html